run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - misspell
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go # Relaxes strict error checking constraints specifically for test files
      linters:
        - errcheck