// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/sale_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/sale_repository.go -destination=internal/repository/mocks/mock_sale_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "CotoChallenge/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSaleRepository is a mock of SaleRepository interface.
type MockSaleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSaleRepositoryMockRecorder
	isgomock struct{}
}

// MockSaleRepositoryMockRecorder is the mock recorder for MockSaleRepository.
type MockSaleRepositoryMockRecorder struct {
	mock *MockSaleRepository
}

// NewMockSaleRepository creates a new mock instance.
func NewMockSaleRepository(ctrl *gomock.Controller) *MockSaleRepository {
	mock := &MockSaleRepository{ctrl: ctrl}
	mock.recorder = &MockSaleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaleRepository) EXPECT() *MockSaleRepositoryMockRecorder {
	return m.recorder
}

// CreateSale mocks base method.
func (m *MockSaleRepository) CreateSale(ctx context.Context, sale domain.Sale) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSale", ctx, sale)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSale indicates an expected call of CreateSale.
func (mr *MockSaleRepositoryMockRecorder) CreateSale(ctx, sale any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSale", reflect.TypeOf((*MockSaleRepository)(nil).CreateSale), ctx, sale)
}

// GetSales mocks base method.
func (m *MockSaleRepository) GetSales(ctx context.Context) ([]domain.Sale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSales", ctx)
	ret0, _ := ret[0].([]domain.Sale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSales indicates an expected call of GetSales.
func (mr *MockSaleRepositoryMockRecorder) GetSales(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSales", reflect.TypeOf((*MockSaleRepository)(nil).GetSales), ctx)
}

// GetSalesByCenter mocks base method.
func (m *MockSaleRepository) GetSalesByCenter(cctx context.Context, enter string) ([]domain.Sale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesByCenter", cctx, enter)
	ret0, _ := ret[0].([]domain.Sale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalesByCenter indicates an expected call of GetSalesByCenter.
func (mr *MockSaleRepositoryMockRecorder) GetSalesByCenter(cctx, enter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesByCenter", reflect.TypeOf((*MockSaleRepository)(nil).GetSalesByCenter), cctx, enter)
}

// GetSalesPercentegeByCenterOverTotalSales mocks base method.
func (m *MockSaleRepository) GetSalesPercentegeByCenterOverTotalSales(ctx context.Context) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesPercentegeByCenterOverTotalSales", ctx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalesPercentegeByCenterOverTotalSales indicates an expected call of GetSalesPercentegeByCenterOverTotalSales.
func (mr *MockSaleRepositoryMockRecorder) GetSalesPercentegeByCenterOverTotalSales(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesPercentegeByCenterOverTotalSales", reflect.TypeOf((*MockSaleRepository)(nil).GetSalesPercentegeByCenterOverTotalSales), ctx)
}
