// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service.go -destination=internal/service/mocks/mock_sale_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "CotoChallenge/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSaleService is a mock of SaleService interface.
type MockSaleService struct {
	ctrl     *gomock.Controller
	recorder *MockSaleServiceMockRecorder
	isgomock struct{}
}

// MockSaleServiceMockRecorder is the mock recorder for MockSaleService.
type MockSaleServiceMockRecorder struct {
	mock *MockSaleService
}

// NewMockSaleService creates a new mock instance.
func NewMockSaleService(ctrl *gomock.Controller) *MockSaleService {
	mock := &MockSaleService{ctrl: ctrl}
	mock.recorder = &MockSaleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaleService) EXPECT() *MockSaleServiceMockRecorder {
	return m.recorder
}

// CreateSale mocks base method.
func (m *MockSaleService) CreateSale(ctx context.Context, vehicle domain.VehicleType, center string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSale", ctx, vehicle, center)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSale indicates an expected call of CreateSale.
func (mr *MockSaleServiceMockRecorder) CreateSale(ctx, vehicle, center any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSale", reflect.TypeOf((*MockSaleService)(nil).CreateSale), ctx, vehicle, center)
}

// GetSales mocks base method.
func (m *MockSaleService) GetSales(ctx context.Context) ([]domain.Sale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSales", ctx)
	ret0, _ := ret[0].([]domain.Sale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSales indicates an expected call of GetSales.
func (mr *MockSaleServiceMockRecorder) GetSales(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSales", reflect.TypeOf((*MockSaleService)(nil).GetSales), ctx)
}

// GetSalesByCenter mocks base method.
func (m *MockSaleService) GetSalesByCenter(ctx context.Context, center string) ([]domain.Sale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesByCenter", ctx, center)
	ret0, _ := ret[0].([]domain.Sale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalesByCenter indicates an expected call of GetSalesByCenter.
func (mr *MockSaleServiceMockRecorder) GetSalesByCenter(ctx, center any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesByCenter", reflect.TypeOf((*MockSaleService)(nil).GetSalesByCenter), ctx, center)
}

// GetSalesPercentegeByCenterOverTotalSales mocks base method.
func (m *MockSaleService) GetSalesPercentegeByCenterOverTotalSales(ctx context.Context) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesPercentegeByCenterOverTotalSales", ctx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalesPercentegeByCenterOverTotalSales indicates an expected call of GetSalesPercentegeByCenterOverTotalSales.
func (mr *MockSaleServiceMockRecorder) GetSalesPercentegeByCenterOverTotalSales(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesPercentegeByCenterOverTotalSales", reflect.TypeOf((*MockSaleService)(nil).GetSalesPercentegeByCenterOverTotalSales), ctx)
}
